### ISSUE TITLE
BUG: Can not access Images page in the Toolbox

### ISSUE THREAD

**Issue by DSCaskey** [Onetchou/Seamly2D#56]
Can only access the Import Image toolbutton from the Toolbox Toolbar or the Tools menu. 

![image](https://github.com/Onetchou/Seamly2D/assets/31944718/b0d8c731-fe92-41f9-8588-051a3ea41cc6)

The QToolbox's need to be put in a Grid layout so all the Page labels display.

![image](https://github.com/Onetchou/Seamly2D/assets/31944718/752aae26-5279-4780-a29d-9bf02a4ea5da)

**Comment by Onetchou** [comment]
Indeed, we should have tested the new widgets using a smaller window. We'll correct it.
