### ISSUE TITLE
BUG: image properties dialog needs to have a fixed width and height

### ISSUE THREAD

**Issue by Onetchou** [Onetchou/Seamly2D#72]
![image](https://github.com/Onetchou/Seamly2D/assets/83351185/212c456c-e21d-4e97-9f3e-834be30cc73d)

**Comment by DSCaskey** [comment]
Doesn't need to be fixed... just make the min dialog width 350 px to match the rest of the tool dialogs. Also the min width of the labels should be incrased to 100px.
